version: "3.8"
name: "helpasaur-king"

services:
  api-server:
    volumes:
      - ./api/src:/app/src

  discord-bot:
    volumes:
      - ./discord/src:/app/src
      - ./lib/helpa-api-client:/lib/helpa-api-client

  twitch-bot:
    volumes:
      - ./twitch/src:/app/src
      - ./lib/helpa-api-client:/lib/helpa-api-client

  web:
    volumes:
      - ./web/src:/app/src

  runnerwatcher:
    volumes:
      - ./runnerwatcher/src:/app/src
      - ./lib/helpa-api-client:/lib/helpa-api-client

  racebot:
    volumes:
      - ./racebot/src:/app/src

  ws-relay:
    volumes:
      - ./ws-relay/src:/app/src
    networks:
      - ext
