version: "3.9"
name: "helpa-monitoring"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - ${UPTIME_KUMA_PORT:-3333}:3001
    volumes:
      - uptime-kuma_data:/app/data
    networks:
      - ext
    extra_hosts:
      # This allows uptime-kuma to connect to the host machine on Linux
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:3001/'', (res) => { process.exit(res.statusCode === 200 || res.statusCode === 302 ? 0 : 1); }).on(''error'', () => { process.exit(1); });"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  uptime-kuma_data:
    name: uptime-kuma_data

networks:
  ext:
    driver: bridge
