services:
  mongo:
    volumes:
      - ./docker-entrypoint-initdb.d/db-init.dev.js:/docker-entrypoint-initdb.d/db-init.dev.js:ro

  api-server:
    volumes:
      - ./api/src:/app/api/src
      - ./lib/types:/lib/types
      - ./lib/helpa-api-client:/lib/helpa-api-client

  discord-bot:
    volumes:
      - ./discord/src:/app/discord/src
      - ./lib/types:/lib/types
      - ./lib/helpa-api-client:/lib/helpa-api-client

  twitch-bot:
    volumes:
      - ./twitch/src:/app/twitch/src
      - ./lib/types:/lib/types
      - ./lib/helpa-api-client:/lib/helpa-api-client

  runnerwatcher:
    volumes:
      - ./runnerwatcher/src:/app/runnerwatcher/src
      - ./lib/types:/lib/types
      - ./lib/helpa-api-client:/lib/helpa-api-client

  racebot:
    volumes:
      - ./racebot/src:/app/racebot/src

  ws-relay:
    volumes:
      - ./ws-relay/src:/app/ws-relay/src
      - ./lib/types:/lib/types
