# Local monitoring setup for testing
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.monitoring.yml up -d

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma-dev
    restart: unless-stopped
    ports:
      - 3013:3001  # Access at http://localhost:3013
    volumes:
      - uptime-kuma_dev_data:/app/data
    networks:
      - ext
      - int
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "node", "extra/healthcheck"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 180s

volumes:
  uptime-kuma_dev_data: