packages:
  # All service directories
  - "api"
  - "discord"
  - "twitch"
  - "web"
  - "runnerwatcher"
  - "racebot"
  - "ws-relay"
  # Shared libraries
  - "lib/api-client"
  - "lib/types"
  # Monitoring utilities
  - "monitoring"
