packages:
  # All service directories
  - "api"
  - "discord"
  - "twitch"
  - "web"
  - "runnerwatcher"
  - "racebot"
  - "ws-relay"
  # Shared libraries
  - "libs/@helpasaur/api-client"
  - "libs/@helpasaur/bot-common"
  - "libs/@helpasaur/types"
  - "libs/twitch-api-client"
  # Monitoring utilities
  - "monitoring"
