name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      custom_domain:
        description: 'Custom domain for GitHub Pages (e.g., preview.helpasaur.com)'
        required: false
        type: string
        default: ''
  workflow_call:  # Allow this workflow to be called by other workflows
    inputs:
      custom_domain:
        description: 'Custom domain for GitHub Pages'
        required: false
        type: string
        default: ''

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./web
        run: pnpm install

      - name: Build web app (with subdirectory)
        if: ${{ !inputs.custom_domain }}
        working-directory: ./web
        env:
          API_HOST: ${{ secrets.API_HOST }}
          TWITCH_APP_CLIENT_ID: ${{ secrets.TWITCH_APP_CLIENT_ID }}
          PUBLIC_URL: /helpasaur-king
        run: |
          pnpm clean
          pnpm build --public-url /helpasaur-king/
      
      - name: Build web app (with custom domain)
        if: ${{ inputs.custom_domain }}
        working-directory: ./web
        env:
          API_HOST: ${{ secrets.API_HOST }}
          TWITCH_APP_CLIENT_ID: ${{ secrets.TWITCH_APP_CLIENT_ID }}
          PUBLIC_URL: /
        run: |
          pnpm clean
          pnpm build

      - name: Add CNAME file
        if: ${{ inputs.custom_domain }}
        run: echo "${{ inputs.custom_domain }}" > ./web/build/CNAME

      - name: Create 404.html for client-side routing
        run: cp ./web/build/index.html ./web/build/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web/build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
