name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Set a branch to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          # add yarn build && yarn start:prod to end of script when we're ready to switch over
          script: |
            cd /srv/helpasaur-king
            git pull
