name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Set a branch to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /srv/helpa
            git pull
            yarn build helpa-base && yarn build && yarn start:prod --force-recreate
